package csexpo.generator.printer

import csexpo.cir.*
import java.io.File
import java.nio.charset.StandardCharsets

/**
 * Renders a [CirModule] into idiomatic C# source files. Mirrors JetBrains' SirPrinter
 * (reference/kotlin/native/swift/sir-printer). In this first milestone the runtime
 * bodies are stubs; the declaration layer (types, signatures, data classes, enums)
 * is complete and compiles as pure C#.
 */
class CSharpPrinter {

    fun print(module: CirModule, outputDir: File) {
        outputDir.mkdirs()
        for (file in module.files) {
            File(outputDir, fileNameFor(file.packageName)).writeText(renderFile(file), StandardCharsets.UTF_8)
        }
        File(outputDir, "Csexpo.Generated.Runtime.cs").writeText(RUNTIME_SOURCE, StandardCharsets.UTF_8)
    }

    private fun fileNameFor(packageName: String): String =
        packageName.split('.').joinToString(".") { it.replaceFirstChar { c -> c.uppercaseChar() } } + ".g.cs"

    // ------------------------------------------------------------------ file

    private fun renderFile(file: CirFile): String {
        val sb = StringBuilder()
        sb.appendLine("// <auto-generated>")
        sb.appendLine("// Generated by csexpo (Kotlin klib -> C#). Do not edit manually.")
        sb.appendLine("// Source package: ${file.packageName}")
        sb.appendLine("// </auto-generated>")
        sb.appendLine("#nullable enable")
        sb.appendLine("using System;")
        sb.appendLine("using System.Collections.Generic;")
        sb.appendLine("using System.Linq;")
        sb.appendLine("using System.Threading.Tasks;")
        sb.appendLine()
        sb.appendLine("namespace ${file.packageName};")
        sb.appendLine()

        val renderer = CSharpTypeRenderer(file.packageName)
        val topLevelFunctions = mutableListOf<CirFunction>()
        val topLevelProperties = mutableListOf<CirProperty>()

        for (decl in file.declarations) {
            when (decl) {
                is CirEnum -> renderEnum(decl, sb, renderer)
                is CirClass -> renderClass(decl, sb, renderer)
                is CirFunction -> topLevelFunctions += decl
                is CirProperty -> topLevelProperties += decl
                is CirTypealias -> Unit // typealiases are resolved at compile time
            }
        }

        if (topLevelFunctions.isNotEmpty() || topLevelProperties.isNotEmpty()) {
            sb.appendLine("/// <summary>Top-level declarations of package ${file.packageName}.</summary>")
            sb.appendLine("public static partial class TopLevelFunctions")
            sb.appendLine("{")
            for (p in topLevelProperties) renderProperty(p, sb, renderer, static = true, indent = "    ")
            for (f in topLevelFunctions) renderFunction(f, sb, renderer, static = true, indent = "    ")
            sb.appendLine("}")
            sb.appendLine()
        }
        return sb.toString()
    }

    // ------------------------------------------------------------------ enums

    private fun renderEnum(e: CirEnum, sb: StringBuilder, renderer: CSharpTypeRenderer) {
        docComment(e.documentation, sb)
        sb.appendLine("public enum ${e.name}")
        sb.appendLine("{")
        for (case in e.cases) {
            sb.appendLine("    ${case.name},")
        }
        sb.appendLine("}")
        sb.appendLine()
    }

    // ------------------------------------------------------------------ classes

    private fun renderClass(c: CirClass, sb: StringBuilder, renderer: CSharpTypeRenderer) {
        docComment(c.documentation, sb)
        val typeParams = c.typeParameters.joinToString(", ") { it.name }.let { if (it.isNotEmpty()) "<$it>" else "" }
        when {
            c.isInterface -> {
                sb.appendLine("public interface ${c.name}$typeParams")
                sb.appendLine("{")
                for (m in c.declarations) {
                    when (m) {
                        is CirFunction -> renderFunction(m, sb, renderer, static = false, indent = "    ")
                        is CirProperty -> renderProperty(m, sb, renderer, static = false, indent = "    ")
                        else -> {}
                    }
                }
                sb.appendLine("}")
            }
            c.isObject -> {
                sb.appendLine("public static class ${c.name}")
                sb.appendLine("{")
                for (m in c.declarations) {
                    when (m) {
                        is CirFunction -> renderFunction(m, sb, renderer, static = true, indent = "    ")
                        is CirProperty -> renderProperty(m, sb, renderer, static = true, indent = "    ")
                        else -> {}
                    }
                }
                sb.appendLine("}")
            }
            c.isData -> {
                // Kotlin data class -> C# record: positional params become properties + equality.
                val params = c.constructorParameters.joinToString(", ") {
                    "${renderer.render(it.type)} ${Pascal(it.name)}"
                }
                sb.appendLine("public sealed record ${c.name}$typeParams($params);")
                sb.appendLine()
            }
            else -> {
                val mod = when {
                    c.isAbstract -> "public abstract"
                    c.isSealed -> "public sealed"
                    else -> "public sealed"
                }
                sb.appendLine("$mod class ${c.name}$typeParams")
                sb.appendLine("{")
                if (c.constructorParameters.isNotEmpty()) {
                    val ctorParams = c.constructorParameters.joinToString(", ") {
                        "${renderer.render(it.type)} ${it.name}"
                    }
                    sb.appendLine("    public ${c.name}($ctorParams)")
                    sb.appendLine("    {")
                    for (cp in c.constructorParameters) {
                        sb.appendLine("        ${Pascal(cp.name)} = ${cp.name};")
                    }
                    sb.appendLine("    }")
                    for (cp in c.constructorParameters) {
                        sb.appendLine("    private readonly ${renderer.render(cp.type)} ${Pascal(cp.name)};")
                    }
                    sb.appendLine()
                }
                for (m in c.declarations) {
                    when (m) {
                        is CirFunction -> renderFunction(m, sb, renderer, static = false, indent = "    ")
                        is CirProperty -> renderProperty(m, sb, renderer, static = false, indent = "    ")
                        else -> {}
                    }
                }
                sb.appendLine("}")
            }
        }
        sb.appendLine()
    }

    // ------------------------------------------------------------------ members

    private fun renderFunction(
        f: CirFunction,
        sb: StringBuilder,
        renderer: CSharpTypeRenderer,
        static: Boolean,
        indent: String,
    ) {
        docComment(f.documentation, sb, indent)
        val retRaw = renderer.render(f.returnType)
        val isVoid = retRaw == "void"
        val retText = when {
            f.isSuspend && isVoid -> "Task"
            f.isSuspend -> "Task<$retRaw>"
            else -> retRaw
        }
        val params = f.parameters.joinToString(", ") { "${renderer.render(it.type)} ${it.name}" }
        val staticText = if (static) "static " else ""
        // Map Kotlin's overrides of Any members onto their C# equivalents.
        val overrideText = if (f.isOverride || f.name in OVERRIDDEN_MEMBERS) "override " else ""
        val csName = when (f.name) {
            "toString" -> "ToString"
            "hashCode" -> "GetHashCode"
            "equals" -> "Equals"
            else -> Pascal(f.name)
        }
        sb.appendLine("${indent}public $overrideText$staticText$retText $csName($params)")
        sb.appendLine("${indent}{")
        sb.appendLine("${indent}    throw new NotImplementedException(\"csexpo: native bridge not yet generated for '${f.name}'.\");")
        sb.appendLine("${indent}}")
        sb.appendLine()
    }

    private fun renderProperty(
        p: CirProperty,
        sb: StringBuilder,
        renderer: CSharpTypeRenderer,
        static: Boolean,
        indent: String,
    ) {
        docComment(p.documentation, sb, indent)
        val staticText = if (static) "static " else ""
        val accessors = if (p.isReadOnly) "{ get; }" else "{ get; set; }"
        sb.appendLine("${indent}public $staticText${renderer.render(p.type)} ${Pascal(p.name)} $accessors")
        sb.appendLine()
    }

    // ------------------------------------------------------------------ helpers

    private fun docComment(doc: String?, sb: StringBuilder, indent: String = "") {
        if (doc.isNullOrBlank()) return
        sb.appendLine("${indent}/// <summary>")
        for (line in doc.lineSequence()) sb.appendLine("${indent}/// ${line.trim()}")
        sb.appendLine("${indent}/// </summary>")
    }

    private fun Pascal(name: String): String = name.replaceFirstChar { it.uppercaseChar() }

    private companion object {
        /** Kotlin members that override `Any` and map to C# Object members. */
        val OVERRIDDEN_MEMBERS = setOf("toString", "hashCode", "equals")

        val RUNTIME_SOURCE = """
// <auto-generated>
// Generated by csexpo. Native bridge placeholders. Do not edit manually.
// </auto-generated>
#nullable enable

namespace Csexpo.Runtime
{
    /// <summary>
    /// Placeholder for the native ABI bridge (milestone 2). Generated declarations
    /// currently throw NotImplementedException until this bridge is wired to the
    /// Kotlin/Native shared library.
    /// </summary>
    public static class NativeBridge
    {
        // Milestone 2: P/Invoke declarations into the KMP shared library land here,
        // generated from the Kotlin/Native C export (same ABI Swift Export relies on).
    }
}
""".trimIndent()
    }
}
