using com.example;

// The "Swift Export" experience for C#: consume the KMP library as if it were native C#.
// All of the interop glue is generated by csexpo into cs-consumer/Generated.

var user = new User("Tom", 30);
Console.WriteLine($"User: {user}");

// Top-level Kotlin functions surface on the generated TopLevelFunctions holder class.
Console.WriteLine(TopLevelFunctions.TopLevelGreeting(user));
Console.WriteLine($"add(1, 2) = {TopLevelFunctions.Add(1, 2)}");

// Kotlin classes surface as C# classes.
var greeter = new Greeter("Hi");
Console.WriteLine(greeter.Greet(user));
Console.WriteLine($"greeter.Version = {greeter.Version}");

// Kotlin enums surface as C# enums.
Console.WriteLine($"Color.RED = {Color.RED}");

// Kotlin collections surface as C# collection interfaces.
Console.WriteLine(string.Join(", ", TopLevelFunctions.ListNames(new[] { user, new User("Ann", 28) })));
